feat(rebrand)!: archifiltre => archifiltre-docs
SocialGouv/archifiltre-docs pull request #1389
Opened 2022-01-28 14:27 UTC by lsagetlethias

Ref: https://github.com/SocialGouv/archifiltre-private/issues/9

2022-02-01 09:27 UTC, Alezco requested changes

2022-02-01 23:53 UTC, lsagetlethias commented on README.md
> +yarn win
Les deux sont builds en même temps avec la même commande (`electron-builder --x64 --ia32 --win portable nsis`) ;

Les `.msi` en revanche sont temporairement désactivés car problème de CI sur virtual env windows 🤷

2022-02-02 15:03 UTC, lsagetlethias commented on src/translations/de.json
> +      "zipNotificationMessage": "Docs kann ZIP-Dateien nicht verarbeiten, bitte entpacken Sie diese, um sie einzulesen",
Yes ! Done

2022-02-02 15:10 UTC, lsagetlethias commented on src/translations/fr.json
> +      "zipNotificationMessage": "Docs ne lit pas les zips, veuillez les décompresser pour les lire",
Done

2022-02-02 16:00 UTC, Alezco approved these changes

2022-02-02 16:38 UTC, merged